# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ROV21_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QMovie, QButtonGroup
from PyQt4.QtCore import QThread, pyqtSignal

#!/usr/bin/env python3
import rospy
import time
from sensor_msgs.msg import Joy
from std_msgs.msg import Int32
from PyQt4 import QtTest
pub = rospy.Publisher('mode', Int32 , queue_size=10000)
pubvision = rospy.Publisher('vmode', Int32, queue_size=10000)
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    global oldvalue
    def setupUi(self, MainWindow):
	self.value1= 1
	self.value2= 2
	self.value3= 3
	self.visionvalue=1
        MainWindow.setObjectName(_fromUtf8("ROV21 - Assiut Robotics"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.background = QtGui.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -10, 1201, 691))
        self.background.setText(_fromUtf8(""))
        self.background.setPixmap(QtGui.QPixmap(_fromUtf8("Background+fixedstuff.png")))
        self.background.setObjectName(_fromUtf8("background"))
        self.rovon = QtGui.QLabel(self.centralwidget)
        self.rovon.setGeometry(QtCore.QRect(229, -89, 51, 31))
        self.rovon.setText(_fromUtf8(""))
        self.rovon.setPixmap(QtGui.QPixmap(_fromUtf8("Yello Dot.png")))
        self.rovon.setObjectName(_fromUtf8("firstdot"))
        self.dcmotorf = QtGui.QLabel(self.centralwidget)
        self.dcmotorf.setGeometry(QtCore.QRect(239, -195, 51, 101))
        self.dcmotorf.setText(_fromUtf8(""))
        self.dcmotorf.setPixmap(QtGui.QPixmap(_fromUtf8("90.png")))
        self.dcmotorf.setObjectName(_fromUtf8("dcmotorf"))

        self.dcmotorb = QtGui.QLabel(self.centralwidget)
        self.dcmotorb.setGeometry(QtCore.QRect(217, -196, 51, 101))
        self.dcmotorb.setText(_fromUtf8(""))
        self.dcmotorb.setPixmap(QtGui.QPixmap(_fromUtf8("-90.png")))
        self.dcmotorb.setObjectName(_fromUtf8("dcmotorb"))

        self.microrov = QtGui.QLabel(self.centralwidget)
        self.microrov.setGeometry(QtCore.QRect(228, -147, 51, 101))
        self.microrov.setText(_fromUtf8(""))
        self.microrov.setPixmap(QtGui.QPixmap(_fromUtf8("Yello Dot.png")))
        self.microrov.setObjectName(_fromUtf8("thirddot"))

        self.led = QtGui.QLabel(self.centralwidget)
        self.led.setGeometry(QtCore.QRect(229, -273, 51, 101))
        self.led.setText(_fromUtf8(""))
        self.led.setPixmap(QtGui.QPixmap(_fromUtf8("Yello Dot.png")))
        self.led.setObjectName(_fromUtf8("led"))
        self.servo1 = QtGui.QLabel(self.centralwidget)
        self.servo1.setGeometry(QtCore.QRect(250, -264, 46, 36))
        self.servo1.setText(_fromUtf8(""))
        self.servo1.setPixmap(QtGui.QPixmap(_fromUtf8("curvedarrowright.png")))
        self.servo1.setObjectName(_fromUtf8("curvedarrowright"))
	self.servo1.setScaledContents(True)
        self.servo2 = QtGui.QLabel(self.centralwidget)
        self.servo2.setGeometry(QtCore.QRect(216, -263, 46, 36))
        self.servo2.setText(_fromUtf8(""))
        self.servo2.setPixmap(QtGui.QPixmap(_fromUtf8("curvedarrowleft.png")))
        self.servo2.setObjectName(_fromUtf8("curvedarrowleft"))
	self.servo2.setScaledContents(True)
        self.camservo1 = QtGui.QLabel(self.centralwidget)
        self.camservo1.setGeometry(QtCore.QRect(250, -132, 46, 36))
        self.camservo1.setText(_fromUtf8(""))
        self.camservo1.setPixmap(QtGui.QPixmap(_fromUtf8("curvedarrowright.png")))
        self.camservo1.setObjectName(_fromUtf8("curvedarrowright"))
	self.camservo1.setScaledContents(True)
        self.camservo2 = QtGui.QLabel(self.centralwidget)
        self.camservo2.setGeometry(QtCore.QRect(216, -132, 46, 36))
        self.camservo2.setText(_fromUtf8(""))
        self.camservo2.setPixmap(QtGui.QPixmap(_fromUtf8("curvedarrowleft.png")))
        self.camservo2.setObjectName(_fromUtf8("curvedarrowleft"))
	self.camservo2.setScaledContents(True)
        self.fmotarr1 = QtGui.QLabel(self.centralwidget)
        self.fmotarr1.setGeometry(QtCore.QRect(711, -107, 71, 41))
        self.fmotarr1.setText(_fromUtf8(""))
        self.fmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("135.png")))
        self.fmotarr1.setObjectName(_fromUtf8("fmotarr1"))
        self.fmotarr2 = QtGui.QLabel(self.centralwidget)
        self.fmotarr2.setGeometry(QtCore.QRect(736, -127, 61, 51))
        self.fmotarr2.setText(_fromUtf8(""))
        self.fmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-45.png")))
        self.fmotarr2.setObjectName(_fromUtf8("fmotarr2"))
        self.secmotarr1 = QtGui.QLabel(self.centralwidget)
        self.secmotarr1.setGeometry(QtCore.QRect(550, -102, 61, 51))
        self.secmotarr1.setText(_fromUtf8(""))
        self.secmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("45.png")))
        self.secmotarr1.setObjectName(_fromUtf8("secmotarr1"))
        self.secmotarr2 = QtGui.QLabel(self.centralwidget)
        self.secmotarr2.setGeometry(QtCore.QRect(529, -129, 51, 41))
        self.secmotarr2.setText(_fromUtf8(""))
        self.secmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-135.png")))
        self.secmotarr2.setObjectName(_fromUtf8("secmotarr2"))
        self.fourthmotarr1 = QtGui.QLabel(self.centralwidget)
        self.fourthmotarr1.setGeometry(QtCore.QRect(528, -268, 71, 41))
        self.fourthmotarr1.setText(_fromUtf8(""))
        self.fourthmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("135.png")))
        self.fourthmotarr1.setObjectName(_fromUtf8("fourthmotarr1"))
        self.fourthmotarr2 = QtGui.QLabel(self.centralwidget)
        self.fourthmotarr2.setGeometry(QtCore.QRect(553, -290, 61, 51))
        self.fourthmotarr2.setText(_fromUtf8(""))
        self.fourthmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-45.png")))
        self.fourthmotarr2.setObjectName(_fromUtf8("fourthmotarr2"))
        self.thirdmotarr2 = QtGui.QLabel(self.centralwidget)
        self.thirdmotarr2.setGeometry(QtCore.QRect(712, -290, 51, 41))
        self.thirdmotarr2.setText(_fromUtf8(""))
        self.thirdmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-135.png")))
        self.thirdmotarr2.setObjectName(_fromUtf8("thirdmotarr2"))
        self.thirdmotarr1 = QtGui.QLabel(self.centralwidget)
        self.thirdmotarr1.setGeometry(QtCore.QRect(733, -263, 61, 51))
        self.thirdmotarr1.setText(_fromUtf8(""))
        self.thirdmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("45.png")))
        self.thirdmotarr1.setObjectName(_fromUtf8("thirdmotarr1"))
        self.fifthmotarr1 = QtGui.QLabel(self.centralwidget)
        self.fifthmotarr1.setGeometry(QtCore.QRect(1041, -169, 61, 61))
        self.fifthmotarr1.setText(_fromUtf8(""))
        self.fifthmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("90.png")))
        self.fifthmotarr1.setObjectName(_fromUtf8("fifthmotarr1"))
        self.fifthmotarr2 = QtGui.QLabel(self.centralwidget)
        self.fifthmotarr2.setGeometry(QtCore.QRect(1041, -210, 51, 51))
        self.fifthmotarr2.setText(_fromUtf8(""))
        self.fifthmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-90.png")))
        self.fifthmotarr2.setObjectName(_fromUtf8("fifthmotarr2"))
        self.sixthmotarr2 = QtGui.QLabel(self.centralwidget)
        self.sixthmotarr2.setGeometry(QtCore.QRect(863, -211, 51, 51))
        self.sixthmotarr2.setText(_fromUtf8(""))
        self.sixthmotarr2.setPixmap(QtGui.QPixmap(_fromUtf8("-90.png")))
        self.sixthmotarr2.setObjectName(_fromUtf8("sixthmotarr2"))
        self.sixthmotarr1 = QtGui.QLabel(self.centralwidget)
        self.sixthmotarr1.setGeometry(QtCore.QRect(863, -170, 61, 61))
        self.sixthmotarr1.setText(_fromUtf8(""))
        self.sixthmotarr1.setPixmap(QtGui.QPixmap(_fromUtf8("90.png")))
        self.sixthmotarr1.setObjectName(_fromUtf8("sixthmotarr1"))
        self.secline = QtGui.QLineEdit(self.centralwidget)
        self.secline.setGeometry(QtCore.QRect(590, -470, 101, 22))
        self.secline.setMouseTracking(False)
        self.secline.setObjectName(_fromUtf8("secline"))
        self.thirdline = QtGui.QLineEdit(self.centralwidget)
        self.thirdline.setGeometry(QtCore.QRect(590, -500, 101, 22))
        self.thirdline.setObjectName(_fromUtf8("thirdline"))
        self.fourthline = QtGui.QLineEdit(self.centralwidget)
        self.fourthline.setGeometry(QtCore.QRect(590, -530, 101, 22))
        self.fourthline.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fourthline.setReadOnly(True)
        self.fourthline.setObjectName(_fromUtf8("fourthline"))
        self.fstline = QtGui.QLineEdit(self.centralwidget)

	
        self.fstline.setGeometry(QtCore.QRect(590, -440, 101, 22))
        self.fstline.setObjectName(_fromUtf8("fstline"))
        self.fifthline = QtGui.QLineEdit(self.centralwidget)
        self.fifthline.setGeometry(QtCore.QRect(870, -440, 101, 22))
        self.fifthline.setObjectName(_fromUtf8("fifthline"))
        self.sixthline = QtGui.QLineEdit(self.centralwidget)
        self.sixthline.setGeometry(QtCore.QRect(870, -470, 101, 22))
        self.sixthline.setReadOnly(True)
        self.sixthline.setObjectName(_fromUtf8("sixthline"))
        self.width = QtGui.QLabel(self.centralwidget)
        self.width.setGeometry(QtCore.QRect(395, -407, 201, 91))
        self.width.setText(_fromUtf8(""))
        self.width.setPixmap(QtGui.QPixmap(_fromUtf8("width.png")))
        self.width.setScaledContents(True)
        self.width.setObjectName(_fromUtf8("width"))
        self.height = QtGui.QLabel(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(395, -437, 201, 91))
        self.height.setText(_fromUtf8(""))
        self.height.setPixmap(QtGui.QPixmap(_fromUtf8("Height.png")))
        self.height.setScaledContents(True)
        self.height.setObjectName(_fromUtf8("height"))
        self.noofmussels = QtGui.QLabel(self.centralwidget)
        self.noofmussels.setGeometry(QtCore.QRect(402, -495, 201, 91))
        self.noofmussels.setText(_fromUtf8(""))
        self.noofmussels.setPixmap(QtGui.QPixmap(_fromUtf8("No.ofmussels.png")))
        self.noofmussels.setScaledContents(True)
        self.noofmussels.setObjectName(_fromUtf8("noofmussels"))
        self.musselscounted = QtGui.QLabel(self.centralwidget)
        self.musselscounted.setGeometry(QtCore.QRect(400, -466, 201, 91))
        self.musselscounted.setText(_fromUtf8(""))
        self.musselscounted.setPixmap(QtGui.QPixmap(_fromUtf8("Mussels counted.png")))
        self.musselscounted.setScaledContents(True)
        self.musselscounted.setObjectName(_fromUtf8("musselscounted"))
        self.calcmusselsbuttonlab = QtGui.QLabel(self.centralwidget)
        self.calcmusselsbuttonlab.setGeometry(QtCore.QRect(460, -470, 231, 201))
        self.calcmusselsbuttonlab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calcmusselsbuttonlab.setText(_fromUtf8(""))
        self.calcmusselsbuttonlab.setPixmap(QtGui.QPixmap(_fromUtf8("Calculate mussels.png")))
        self.calcmusselsbuttonlab.setScaledContents(True)
        self.calcmusselsbuttonlab.setObjectName(_fromUtf8("calcmusselsbuttonlab"))
        self.calcmusselsbutton = QtGui.QPushButton(self.centralwidget)
        self.calcmusselsbutton.setGeometry(QtCore.QRect(490, 570, 161, 28))
        self.calcmusselsbutton.setText(_fromUtf8(""))
        self.calcmusselsbutton.setFlat(True)
        self.calcmusselsbutton.setObjectName(_fromUtf8("calcmusselsbutton"))
	self.calcmusselsbutton.clicked.connect(self.task3_1)
        self.filterationrate = QtGui.QLabel(self.centralwidget)
        self.filterationrate.setGeometry(QtCore.QRect(690, -407, 201, 91))
        self.filterationrate.setText(_fromUtf8(""))
        self.filterationrate.setPixmap(QtGui.QPixmap(_fromUtf8("filterationrate.png")))
        self.filterationrate.setScaledContents(True)
        self.filterationrate.setObjectName(_fromUtf8("filterationrate"))
        self.totalfilteration = QtGui.QLabel(self.centralwidget)
        self.totalfilteration.setGeometry(QtCore.QRect(690, -436, 201, 91))
        self.totalfilteration.setText(_fromUtf8(""))
        self.totalfilteration.setPixmap(QtGui.QPixmap(_fromUtf8("Total filteration1.png")))
        self.totalfilteration.setScaledContents(True)
        self.totalfilteration.setObjectName(_fromUtf8("totalfilteration"))
        self.totalfilterationbutlab = QtGui.QLabel(self.centralwidget)
        self.totalfilterationbutlab.setGeometry(QtCore.QRect(720, -400, 261, 221))
        self.totalfilterationbutlab.setText(_fromUtf8(""))
        self.totalfilterationbutlab.setPixmap(QtGui.QPixmap(_fromUtf8("Total filteration.png")))
        self.totalfilterationbutlab.setScaledContents(True)
        self.totalfilterationbutlab.setObjectName(_fromUtf8("totalfilterationbutlab"))
        self.totfilterbutton = QtGui.QPushButton(self.centralwidget)
        self.totfilterbutton.setGeometry(QtCore.QRect(760, -510, 181, 28))
        self.totfilterbutton.setText(_fromUtf8(""))
        self.totfilterbutton.setFlat(True)
        self.totfilterbutton.setObjectName(_fromUtf8("totfilterbutton"))
	self.totfilterbutton.clicked.connect(self.task3_2)
        self.holder = QtGui.QLabel(self.centralwidget)
        self.holder.setGeometry(QtCore.QRect(410, -400, 661, 231))
        self.holder.setText(_fromUtf8(""))
        self.holder.setPixmap(QtGui.QPixmap(_fromUtf8("holder22.png")))
        self.holder.setObjectName(_fromUtf8("holder"))

        self.movingback = QtGui.QLabel(self.centralwidget)
        self.movingback.setGeometry(90, -420, 251, 171)
        self.movingback.setText(_fromUtf8(""))
        self.movingback.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Backward.png")))
        self.movingback.setScaledContents(True)
        self.movingback.setObjectName(_fromUtf8("movingback"))
        self.movingdown = QtGui.QLabel(self.centralwidget)
        self.movingdown.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingdown.setText(_fromUtf8(""))
        self.movingdown.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Downward.png")))
        self.movingdown.setScaledContents(True)
        self.movingdown.setObjectName(_fromUtf8("movingdown"))
        self.movingforward = QtGui.QLabel(self.centralwidget)
        self.movingforward.setGeometry(90, -420, 251, 171)
        self.movingforward.setText(_fromUtf8(""))
        self.movingforward.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Forward.png")))
        self.movingforward.setScaledContents(True)
        self.movingforward.setObjectName(_fromUtf8("movingforward"))
        self.movingleft = QtGui.QLabel(self.centralwidget)
        self.movingleft.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingleft.setText(_fromUtf8(""))
        self.movingleft.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Left.png")))
        self.movingleft.setScaledContents(True)
        self.movingleft.setObjectName(_fromUtf8("movingleft"))
        self.movingright = QtGui.QLabel(self.centralwidget)
        self.movingright.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingright.setText(_fromUtf8(""))
        self.movingright.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Right.png")))
        self.movingright.setScaledContents(True)
        self.movingright.setObjectName(_fromUtf8("movingright"))
        self.movingup = QtGui.QLabel(self.centralwidget)
        self.movingup.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingup.setText(_fromUtf8(""))
        self.movingup.setPixmap(QtGui.QPixmap(_fromUtf8("Moving Upward.png")))
        self.movingup.setScaledContents(True)
        self.movingup.setObjectName(_fromUtf8("movingup"))
        self.rotatingleft = QtGui.QLabel(self.centralwidget)
        self.rotatingleft.setGeometry(98, -480, 241, 51)
        self.rotatingleft.setText(_fromUtf8(""))
        self.rotatingleft.setPixmap(QtGui.QPixmap(_fromUtf8("RotatingLeft.png")))
        self.rotatingleft.setScaledContents(True)
        self.rotatingleft.setObjectName(_fromUtf8("rotatingleft"))
        self.rotatingright = QtGui.QLabel(self.centralwidget)
        self.rotatingright.setGeometry(98, -480, 241, 51)
        self.rotatingright.setText(_fromUtf8(""))
        self.rotatingright.setPixmap(QtGui.QPixmap(_fromUtf8("RotatingRight.png")))
        self.rotatingright.setScaledContents(True)
        self.rotatingright.setObjectName(_fromUtf8("rotatingright"))
        self.grippero = QtGui.QLabel(self.centralwidget)
        self.grippero.setGeometry(QtCore.QRect(90, -460, 251, 171))
        self.grippero.setText(_fromUtf8(""))
        self.grippero.setPixmap(QtGui.QPixmap(_fromUtf8("Gripperopen.png")))
        self.grippero.setObjectName(_fromUtf8("gripperopen"))
        self.gripperc = QtGui.QLabel(self.centralwidget)
        self.gripperc.setGeometry(QtCore.QRect(77, 460, 251, 171))
        self.gripperc.setText(_fromUtf8(""))
        self.gripperc.setPixmap(QtGui.QPixmap(_fromUtf8("Gripperclosed.png")))
        self.gripperc.setObjectName(_fromUtf8("gripperclosed"))
	self.bg1= QButtonGroup()
	self.bg2 = QButtonGroup()
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(670, 386, 21, 20))
        self.radioButton.setText(_fromUtf8(""))

	self.radioButton.clicked.connect(self.tasks)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton.setChecked(True)
        self.task1rad = QtGui.QLabel(self.centralwidget)
        self.task1rad.setGeometry(QtCore.QRect(683, 388, 71, 16))
        self.task1rad.setText(_fromUtf8(""))
        self.task1rad.setPixmap(QtGui.QPixmap(_fromUtf8("task1_rad.png")))
        self.task1rad.setScaledContents(True)
        self.task1rad.setObjectName(_fromUtf8("task1rad"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(800, 386, 21, 20))
        self.radioButton_2.setText(_fromUtf8(""))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
	self.radioButton_2.clicked.connect(self.tasks)
        self.task2rad = QtGui.QLabel(self.centralwidget)
        self.task2rad.setGeometry(QtCore.QRect(812, 388, 71, 16))
        self.task2rad.setText(_fromUtf8(""))
        self.task2rad.setPixmap(QtGui.QPixmap(_fromUtf8("Task2_rad.png")))
        self.task2rad.setScaledContents(True)
        self.task2rad.setObjectName(_fromUtf8("task2rad"))
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(928, 386, 21, 20))
        self.radioButton_3.setText(_fromUtf8(""))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
	self.radioButton_3.clicked.connect(self.tasks)
        self.task3rad = QtGui.QLabel(self.centralwidget)
        self.task3rad.setGeometry(QtCore.QRect(940, 388, 71, 16))
        self.task3rad.setText(_fromUtf8(""))
        self.task3rad.setPixmap(QtGui.QPixmap(_fromUtf8("Task3_rad.png")))
        self.task3rad.setScaledContents(True)
        self.task3rad.setObjectName(_fromUtf8("task3rad"))
	self.bg1.addButton(self.radioButton)
	self.bg1.addButton(self.radioButton_2)
	self.bg1.addButton(self.radioButton_3)

        self.normalmode = QtGui.QRadioButton(self.centralwidget)
        self.normalmode.setGeometry(QtCore.QRect(319, 187, 21, 20))
        self.normalmode.setText(_fromUtf8(""))
        self.normalmode.setObjectName(_fromUtf8("normalmode"))
	self.normalmode.clicked.connect(self.modes)
        self.micromode = QtGui.QRadioButton(self.centralwidget)
        self.micromode.setGeometry(QtCore.QRect(319, 242, 21, 20))
        self.micromode.setText(_fromUtf8(""))
        self.micromode.setObjectName(_fromUtf8("micromode"))
	self.micromode.clicked.connect(self.modes)

        self.offmode = QtGui.QRadioButton(self.centralwidget)
        self.offmode.setGeometry(QtCore.QRect(319, 297, 21, 20))
        self.offmode.setText(_fromUtf8(""))
        self.offmode.setObjectName(_fromUtf8("offmode"))
	self.offmode.setChecked(True)
	self.offmode.clicked.connect(self.modes)



	self.bg2.addButton(self.normalmode)
	self.bg2.addButton(self.micromode)
	self.bg2.addButton(self.offmode)
        self.t3_1ch = QtGui.QCheckBox(self.centralwidget)
        self.t3_1ch.setGeometry(QtCore.QRect(1030, -440, 16, 20))
        self.t3_1ch.setText(_fromUtf8(""))
        self.t3_1ch.setObjectName(_fromUtf8("t3_1ch"))
        self.t3_2ch = QtGui.QCheckBox(self.centralwidget)
        self.t3_2ch.setGeometry(QtCore.QRect(1030, -483, 16, 20))
        self.t3_2ch.setText(_fromUtf8(""))
        self.t3_2ch.setObjectName(_fromUtf8("t3_2ch"))
        self.t3_3ch = QtGui.QCheckBox(self.centralwidget)
        self.t3_3ch.setGeometry(QtCore.QRect(1030, -525, 16, 20))
        self.t3_3ch.setText(_fromUtf8(""))
        self.t3_3ch.setObjectName(_fromUtf8("t3_3ch"))
        self.t3_4ch = QtGui.QCheckBox(self.centralwidget)
        self.t3_4ch.setGeometry(QtCore.QRect(1030, -570, 16, 20))
        self.t3_4ch.setText(_fromUtf8(""))
        self.t3_4ch.setObjectName(_fromUtf8("t3_4ch"))
	self.t3_4ch.stateChanged.connect(self.state_changed3)
        self.t3_1 = QtGui.QLabel(self.centralwidget)
        self.t3_1.setGeometry(QtCore.QRect(1050, -439, 55, 21))
        self.t3_1.setText(_fromUtf8(""))
        self.t3_1.setPixmap(QtGui.QPixmap(_fromUtf8("3.1.png")))
        self.t3_1.setObjectName(_fromUtf8("t3_1"))
        self.t3_2 = QtGui.QLabel(self.centralwidget)
        self.t3_2.setGeometry(QtCore.QRect(1050, -483, 55, 21))
        self.t3_2.setText(_fromUtf8(""))
        self.t3_2.setPixmap(QtGui.QPixmap(_fromUtf8("3.2.png")))
        self.t3_2.setObjectName(_fromUtf8("t3_2"))
        self.t3_3 = QtGui.QLabel(self.centralwidget)
        self.t3_3.setGeometry(QtCore.QRect(1050, -525, 55, 21))
        self.t3_3.setText(_fromUtf8(""))
        self.t3_3.setPixmap(QtGui.QPixmap(_fromUtf8("3.3.png")))
        self.t3_3.setObjectName(_fromUtf8("t3_3"))
        self.t3_4 = QtGui.QLabel(self.centralwidget)
        self.t3_4.setGeometry(QtCore.QRect(1050, -570, 55, 21))
        self.t3_4.setText(_fromUtf8(""))
        self.t3_4.setPixmap(QtGui.QPixmap(_fromUtf8("3.4.png")))
        self.t3_4.setObjectName(_fromUtf8("t3_4"))
        self.t1_1ch = QtGui.QCheckBox(self.centralwidget)
        self.t1_1ch.setGeometry(QtCore.QRect(458, 465, 21, 20))
        self.t1_1ch.setText(_fromUtf8(""))
        self.t1_1ch.setObjectName(_fromUtf8("t1_1ch"))
        self.t1_2ch = QtGui.QCheckBox(self.centralwidget)
        self.t1_2ch.setGeometry(QtCore.QRect(458, 518, 21, 20))
        self.t1_2ch.setText(_fromUtf8(""))
        self.t1_2ch.setObjectName(_fromUtf8("t1_2ch"))
        self.t1_1 = QtGui.QLabel(self.centralwidget)
        self.t1_1.setGeometry(QtCore.QRect(410, 450, 871, 131))
        self.t1_1.setText(_fromUtf8(""))
        self.t1_1.setPixmap(QtGui.QPixmap(_fromUtf8("tasks1.png")))
        self.t1_1.setObjectName(_fromUtf8("t1_1"))
	self.t1_2ch.stateChanged.connect(self.state_changed)
        self.t2_1ch = QtGui.QCheckBox(self.centralwidget)
        self.t2_1ch.setGeometry(QtCore.QRect(530, -480, 16, 20))
        self.t2_1ch.setText(_fromUtf8(""))
        self.t2_1ch.setObjectName(_fromUtf8("t2_1ch"))
        self.t2_2ch = QtGui.QCheckBox(self.centralwidget)
        self.t2_2ch.setGeometry(QtCore.QRect(740, -480, 21, 20))
        self.t2_2ch.setText(_fromUtf8(""))
        self.t2_2ch.setObjectName(_fromUtf8("t2_2ch"))
        self.t2_3ch = QtGui.QCheckBox(self.centralwidget)
        self.t2_3ch.setGeometry(QtCore.QRect(950, -480, 21, 20))
        self.t2_3ch.setText(_fromUtf8(""))
        self.t2_3ch.setObjectName(_fromUtf8("t2_3ch"))
        self.t2_4ch = QtGui.QCheckBox(self.centralwidget)
        self.t2_4ch.setGeometry(QtCore.QRect(630, -540, 21, 20))
        self.t2_4ch.setText(_fromUtf8(""))
        self.t2_4ch.setObjectName(_fromUtf8("t2_4ch"))
        self.t2_1 = QtGui.QLabel(self.centralwidget)
        self.t2_1.setGeometry(QtCore.QRect(410, -420, 781, 211))
        self.t2_1.setText(_fromUtf8(""))
        self.t2_1.setPixmap(QtGui.QPixmap(_fromUtf8("tasks2.png")))
        self.t2_1.setObjectName(_fromUtf8("t2_1"))
        self.t2_4ch_2 = QtGui.QCheckBox(self.centralwidget)
        self.t2_4ch_2.setGeometry(QtCore.QRect(460, -584, 21, 20))
        self.t2_4ch_2.setText(_fromUtf8(""))
        self.t2_4ch_2.setObjectName(_fromUtf8("t2_4ch_2"))
	self.t2_4ch_2.stateChanged.connect(self.state_changed2)
        self.task1done = QtGui.QLabel(self.centralwidget)
        self.task1done.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.task1done.setText(_fromUtf8(""))
        self.task1done.setPixmap(QtGui.QPixmap(_fromUtf8("Task1.png")))
        self.task1done.setScaledContents(True)
        self.task1done.setObjectName(_fromUtf8("task1done"))
        self.task2done = QtGui.QLabel(self.centralwidget)
        self.task2done.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.task2done.setText(_fromUtf8(""))
        self.task2done.setPixmap(QtGui.QPixmap(_fromUtf8("Task2.png")))
        self.task2done.setScaledContents(True)
        self.task2done.setObjectName(_fromUtf8("task2done"))
        self.task1done_3 = QtGui.QLabel(self.centralwidget)
        self.task1done_3.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.task1done_3.setText(_fromUtf8(""))
        self.task1done_3.setPixmap(QtGui.QPixmap(_fromUtf8("Task3.png")))
        self.task1done_3.setScaledContents(True)
        self.task1done_3.setObjectName(_fromUtf8("task1done_3"))
        self.firelabel = QtGui.QLabel(self.centralwidget)
        self.firelabel.setGeometry(QtCore.QRect(70, 400, 281, 211))
        self.firelabel.setText(_fromUtf8(""))
        self.firelabel.setObjectName(_fromUtf8("firelabel"))
	self.movie= QMovie("fire.gif")
        self.firelabel.setScaledContents(True)
        self.background.raise_()
        self.rovon.raise_()
        self.dcmotorf.raise_()
        self.dcmotorb.raise_()
        self.microrov.raise_()

        self.fmotarr1.raise_()
        self.fmotarr2.raise_()
        self.secmotarr1.raise_()
        self.secmotarr2.raise_()
        self.fourthmotarr1.raise_()
        self.fourthmotarr2.raise_()
        self.thirdmotarr2.raise_()
        self.thirdmotarr1.raise_()
        self.width.raise_()
        self.height.raise_()
        self.noofmussels.raise_()
        self.musselscounted.raise_()
        self.calcmusselsbuttonlab.raise_()
        self.filterationrate.raise_()
        self.totalfilteration.raise_()
        self.totalfilterationbutlab.raise_()
        self.holder.raise_()
        self.thirdline.raise_()
        self.fstline.raise_()
        self.secline.raise_()
        self.fourthline.raise_()
        self.totfilterbutton.raise_()
        self.fifthline.raise_()
        self.sixthline.raise_()
        self.calcmusselsbutton.raise_()
        self.microrov.raise_()
        self.led.raise_()


        self.movingback.raise_()
        self.movingdown.raise_()
        self.movingforward.raise_()
        self.movingleft.raise_()
        self.movingright.raise_()
        self.movingup.raise_()
        self.rotatingleft.raise_()
        self.rotatingright.raise_()
        self.radioButton.raise_()
        self.task1rad.raise_()
        self.radioButton_2.raise_()
        self.task2rad.raise_()
        self.radioButton_3.raise_()
        self.task3rad.raise_()
        self.t1_1ch.raise_()
        self.t1_2ch.raise_()
        self.t1_1.raise_()
        self.t2_1ch.raise_()
        self.t2_2ch.raise_()
        self.t2_3ch.raise_()
        self.t2_4ch.raise_()
        self.t2_4ch_2.raise_()
        self.t2_1.raise_()
        self.t3_1ch.raise_()
        self.t3_2ch.raise_()
        self.t3_3ch.raise_()
        self.t3_4ch.raise_()
        self.t3_1.raise_()
        self.t3_2.raise_()
        self.t3_3.raise_()
        self.t3_4.raise_()
        self.task1done.raise_()
        self.task2done.raise_()
        self.task1done_3.raise_()
        self.firelabel.raise_()
        self.fifthmotarr1.raise_()
        self.fifthmotarr2.raise_()
        self.sixthmotarr2.raise_()
        self.sixthmotarr1.raise_()
        self.t1_1ch.raise_()
        self.t1_2ch.raise_()
        self.t2_1ch.raise_()
        self.t2_2ch.raise_()
        self.t2_3ch.raise_()
        self.t2_4ch.raise_()
        self.t2_4ch_2.raise_()
        self.gripperc.raise_()    
        self.grippero.raise_()
        self.servo1.raise_()
        self.camservo1.raise_()
        self.servo2.raise_()
        self.camservo2.raise_()
	self.dcmotorb.raise_()
	self.normalmode.raise_()
	self.micromode.raise_()
	self.microrov.raise_()
	self.offmode.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("ROV21 - Assiut Robotics", "ROV21 - Assiut Robotics", None))
	self.oldvalue = 1
#	self.start_threading()
	self.listener() 


    def state_changed(self):
	if(self.t1_1ch.isChecked() and self.t1_2ch.isChecked()):
        	self.grippero.setGeometry(QtCore.QRect(90, -460, 251, 171))
      		self.gripperc.setGeometry(QtCore.QRect(77, -460, 251, 171))
		self.task1done.setGeometry(QtCore.QRect(90, 420, 251, 171))	
		QtTest.QTest.qWait(1000)
		self.task1done.setGeometry(QtCore.QRect(90, -420, 251, 171))
        	self.firelabel.setGeometry(QtCore.QRect(70, 400, 281, 211))
		self.firelabel.setMovie(self.movie)
		self.movie.start()
		QtTest.QTest.qWait(1000)
		self.movie.stop()
       		self.firelabel.setGeometry(QtCore.QRect(70, -400, 281, 211))
      		self.gripperc.setGeometry(QtCore.QRect(77, 460, 251, 171))

    def state_changed2(self):
	if(self.t2_1ch.isChecked() and self.t2_2ch.isChecked() and self.t2_3ch.isChecked() and self.t2_4ch.isChecked() and self.t2_4ch_2.isChecked()):
        	self.grippero.setGeometry(QtCore.QRect(90, -460, 251, 171))
      		self.gripperc.setGeometry(QtCore.QRect(77, -460, 251, 171))
        	self.task2done.setGeometry(QtCore.QRect(90, 420, 251, 171))
		QtTest.QTest.qWait(1000)
       		self.task2done.setGeometry(QtCore.QRect(90, -420, 251, 171))
        	self.firelabel.setGeometry(QtCore.QRect(70, 400, 281, 211))
		self.firelabel.setMovie(self.movie)
		self.movie.start()
		QtTest.QTest.qWait(1000)
		self.movie.stop()
       		self.firelabel.setGeometry(QtCore.QRect(70, -400, 281, 211))
      		self.gripperc.setGeometry(QtCore.QRect(77, 460, 251, 171))

    def state_changed3(self):
	if(self.t3_1ch.isChecked() and self.t3_2ch.isChecked() and self.t3_3ch.isChecked() and self.t3_4ch.isChecked() ):
        	self.grippero.setGeometry(QtCore.QRect(90, -460, 251, 171))
      		self.gripperc.setGeometry(QtCore.QRect(77, -460, 251, 171))
        	self.task1done_3.setGeometry(QtCore.QRect(90, 420, 251, 171))
		QtTest.QTest.qWait(1000)
        	self.task1done_3.setGeometry(QtCore.QRect(90, -420, 251, 171))
        	self.firelabel.setGeometry(QtCore.QRect(70, 400, 281, 211))
		self.firelabel.setMovie(self.movie)
		self.movie.start()
		QtTest.QTest.qWait(1000)
		self.movie.stop()
       		self.firelabel.setGeometry(QtCore.QRect(70, -400, 281, 211))
      		self.gripperc.setGeometry(QtCore.QRect(77, 460, 251, 171))

    def task3_1(self):
	width = self.fstline.text()
	height = self.secline.text()
	muscount = self.thirdline.text()
	nofmus = (int(width)*int(height))*4*int(muscount)
	self.fourthline.setText(str(nofmus))

    def task3_2(self):
	fr=self.fifthline.text()
	nofmus = self.fourthline.text()
	tot = (float(nofmus) * float(fr))
	self.sixthline.setText(str(tot))
    def modes (self):
	if (self.micromode.isChecked()):
		pub.publish(Int32(self.value2))
		self.microrov.setGeometry(QtCore.QRect(228, 157, 51, 101))
	elif (self.normalmode.isChecked()):
		pub.publish(Int32(self.value1))
		self.microrov.setGeometry(QtCore.QRect(228, -147, 51, 101))
	elif (self.offmode.isChecked()):
		pub.publish(Int32(self.value3))
		self.microrov.setGeometry(QtCore.QRect(228, -147, 51, 101))  
    def visionmode(self):
	pubvision.publish(Int32(self.visionvalue))
		
    def tasks (self):
	if (self.radioButton.isChecked()):

        	self.t1_1.setGeometry(QtCore.QRect(410, 450, 871, 131))
        	self.t1_1ch.setGeometry(QtCore.QRect(458, 465, 21, 20))
        	self.t1_2ch.setGeometry(QtCore.QRect(458, 518, 21, 20))
        	self.t2_1.setGeometry(QtCore.QRect(560, -480, 81, 21))
        	self.t2_2ch.setGeometry(QtCore.QRect(740, -480, 21, 20))
        	self.t2_1ch.setGeometry(QtCore.QRect(530, -480, 16, 20))
        	self.t2_2ch.setGeometry(QtCore.QRect(740, -480, 21, 20))
        	self.t2_3ch.setGeometry(QtCore.QRect(950, -480, 21, 20))
        	self.t2_4ch.setGeometry(QtCore.QRect(630, -540, 21, 20))
        	self.t2_4ch_2.setGeometry(QtCore.QRect(460, -584, 21, 20))
        	self.t3_1ch.setGeometry(QtCore.QRect(1030, -440, 16, 20))
        	self.t3_2ch.setGeometry(QtCore.QRect(1030, -483, 16, 20))
        	self.t3_3ch.setGeometry(QtCore.QRect(1030, -525, 16, 20))
        	self.t3_4ch.setGeometry(QtCore.QRect(1030, -570, 16, 20))
        	self.t3_1.setGeometry(QtCore.QRect(1050, -439, 55, 21))
        	self.t3_2.setGeometry(QtCore.QRect(1050, -483, 55, 21))
        	self.t3_3.setGeometry(QtCore.QRect(1050, -525, 55, 21))
        	self.t3_4.setGeometry(QtCore.QRect(1050, -570, 55, 21))
        	self.holder.setGeometry(QtCore.QRect(410, -400, 661, 231))
		self.totfilterbutton.setGeometry(QtCore.QRect(760, -510, 181, 28))  
      		self.totalfilterationbutlab.setGeometry(QtCore.QRect(720, -400, 261, 221))
		self.totalfilteration.setGeometry(QtCore.QRect(690, -436, 201, 91)) 
       		self.filterationrate.setGeometry(QtCore.QRect(690, -407, 201, 91))
        	self.calcmusselsbutton.setGeometry(QtCore.QRect(490, -570, 161, 28))
        	self.calcmusselsbuttonlab.setGeometry(QtCore.QRect(460, -470, 231, 201))
        	self.musselscounted.setGeometry(QtCore.QRect(400, -466, 201, 91)) 
       		self.noofmussels.setGeometry(QtCore.QRect(402, -495, 201, 91)) 
       		self.height.setGeometry(QtCore.QRect(395, -437, 201, 91))
		self.width.setGeometry(QtCore.QRect(395, -407, 201, 91)) 
       		self.sixthline.setGeometry(QtCore.QRect(870, -470, 101, 22))
        	self.fifthline.setGeometry(QtCore.QRect(870, -440, 101, 22))
	        self.fourthline.setGeometry(QtCore.QRect(590, -530, 101, 22))
	        self.thirdline.setGeometry(QtCore.QRect(590, -500, 101, 22)) 
		self.secline.setGeometry(QtCore.QRect(590, -470, 101, 22))       
		self.fstline.setGeometry(QtCore.QRect(590, -440, 101, 22))
	elif (self.radioButton_2.isChecked()):
        	self.t1_1.setGeometry(QtCore.QRect(410, -450, 871, 131))
        	self.t1_1ch.setGeometry(QtCore.QRect(458, -465, 21, 20))
        	self.t1_2ch.setGeometry(QtCore.QRect(458, -518, 21, 20))
        	self.t2_1.setGeometry(QtCore.QRect(410, 420, 781, 211))
        	self.t2_1ch.setGeometry(QtCore.QRect(460, 441, 16, 20))
        	self.t2_2ch.setGeometry(QtCore.QRect(460, 480, 21, 20))
        	self.t2_3ch.setGeometry(QtCore.QRect(460, 513, 21, 20))
        	self.t2_4ch.setGeometry(QtCore.QRect(460, 549, 21, 20))
        	self.t2_4ch_2.setGeometry(QtCore.QRect(460, 584, 21, 20))
        	self.t3_1ch.setGeometry(QtCore.QRect(1030, -440, 16, 20))
        	self.t3_2ch.setGeometry(QtCore.QRect(1030, -483, 16, 20))
        	self.t3_3ch.setGeometry(QtCore.QRect(1030, -525, 16, 20))
        	self.t3_4ch.setGeometry(QtCore.QRect(1030, -570, 16, 20))
        	self.t3_1.setGeometry(QtCore.QRect(1050, -439, 55, 21))
        	self.t3_2.setGeometry(QtCore.QRect(1050, -483, 55, 21))
        	self.t3_3.setGeometry(QtCore.QRect(1050, -525, 55, 21))
        	self.t3_4.setGeometry(QtCore.QRect(1050, -570, 55, 21))
        	self.holder.setGeometry(QtCore.QRect(410, -400, 661, 231))
		self.totfilterbutton.setGeometry(QtCore.QRect(760, -510, 181, 28))  
      		self.totalfilterationbutlab.setGeometry(QtCore.QRect(720, -400, 261, 221))
		self.totalfilteration.setGeometry(QtCore.QRect(690, -436, 201, 91)) 
       		self.filterationrate.setGeometry(QtCore.QRect(690, -407, 201, 91))
        	self.calcmusselsbutton.setGeometry(QtCore.QRect(490, -570, 161, 28))
        	self.calcmusselsbuttonlab.setGeometry(QtCore.QRect(460, -470, 231, 201))
        	self.musselscounted.setGeometry(QtCore.QRect(400, -466, 201, 91)) 
       		self.noofmussels.setGeometry(QtCore.QRect(402, -495, 201, 91)) 
       		self.height.setGeometry(QtCore.QRect(395, -437, 201, 91))
		self.width.setGeometry(QtCore.QRect(395, -407, 201, 91)) 
       		self.sixthline.setGeometry(QtCore.QRect(870, -470, 101, 22))
        	self.fifthline.setGeometry(QtCore.QRect(870, -440, 101, 22))
	        self.fourthline.setGeometry(QtCore.QRect(590, -530, 101, 22))
	        self.thirdline.setGeometry(QtCore.QRect(590, -500, 101, 22)) 
		self.secline.setGeometry(QtCore.QRect(590, -470, 101, 22))       
		self.fstline.setGeometry(QtCore.QRect(590, -440, 101, 22))

	elif (self.radioButton_3.isChecked()):
        	self.t1_1.setGeometry(QtCore.QRect(610, -502, 55, 16))
	        self.t1_1ch.setGeometry(QtCore.QRect(580, -500, 21, 20))
        	self.t1_2ch.setGeometry(QtCore.QRect(860, -500, 21, 20))
        	self.t2_1.setGeometry(QtCore.QRect(560, -480, 81, 21))
        	self.t2_1ch.setGeometry(QtCore.QRect(530, -480, 20, 20))
        	self.t2_2ch.setGeometry(QtCore.QRect(740, -480, 21, 20))
        	self.t2_3ch.setGeometry(QtCore.QRect(950, -480, 21, 20))
        	self.t2_4ch.setGeometry(QtCore.QRect(630, -540, 21, 20))
        	self.t2_4ch_2.setGeometry(QtCore.QRect(460, -584, 21, 20))
        	self.t3_1ch.setGeometry(QtCore.QRect(1030, 440, 20, 20))
        	self.t3_2ch.setGeometry(QtCore.QRect(1030, 483, 20, 20))
        	self.t3_3ch.setGeometry(QtCore.QRect(1030, 525, 20, 20))
        	self.t3_4ch.setGeometry(QtCore.QRect(1030, 570, 20, 20))
        	self.t3_1.setGeometry(QtCore.QRect(1050, 439, 55, 21))
        	self.t3_2.setGeometry(QtCore.QRect(1050, 483, 55, 21))
        	self.t3_3.setGeometry(QtCore.QRect(1050, 525, 55, 21))
        	self.t3_4.setGeometry(QtCore.QRect(1050, 570, 55, 21))
        	self.holder.setGeometry(QtCore.QRect(410, 400, 661, 231))
		self.totfilterbutton.setGeometry(QtCore.QRect(760, 510, 181, 28))  
      		self.totalfilterationbutlab.setGeometry(QtCore.QRect(720, 400, 261, 221))
		self.totalfilteration.setGeometry(QtCore.QRect(690, 436, 201, 91)) 
       		self.filterationrate.setGeometry(QtCore.QRect(690, 407, 201, 91))
        	self.calcmusselsbutton.setGeometry(QtCore.QRect(490, 570, 161, 28))
        	self.calcmusselsbuttonlab.setGeometry(QtCore.QRect(460, 470, 231, 201))
        	self.musselscounted.setGeometry(QtCore.QRect(400, 466, 201, 91)) 
       		self.noofmussels.setGeometry(QtCore.QRect(402, 495, 201, 91)) 
       		self.height.setGeometry(QtCore.QRect(395, 437, 201, 91))
		self.width.setGeometry(QtCore.QRect(395, 407, 201, 91)) 
       		self.sixthline.setGeometry(QtCore.QRect(870, 470, 101, 22))
        	self.fifthline.setGeometry(QtCore.QRect(870, 440, 101, 22))
	        self.fourthline.setGeometry(QtCore.QRect(590, 530, 101, 22))
	        self.thirdline.setGeometry(QtCore.QRect(590, 500, 101, 22)) 
		self.secline.setGeometry(QtCore.QRect(590, 470, 101, 22))       
		self.fstline.setGeometry(QtCore.QRect(590, 440, 101, 22))


		 	
    def listener (self):
	rospy.init_node('joysub', anonymous=True)
	pub.publish(Int32(self.value3))
	rospy.Subscriber("joy", Joy, self.callback)


#    def start_threading(self):
#	self.thread_started = ThreadClass()
#	self.thread_started.label1_changed.connect(self.firstdot.setGeometry)
#	self.thread_started.start()

    def callback(self,msg):
	if (self.normalmode.isChecked()):
		pub.publish(Int32(self.value1))
		self.microrov.setGeometry(QtCore.QRect(228, -147, 51, 101))
		if msg.axes[0]>0:
			self.fmotarr1.setGeometry(QtCore.QRect(711, 107, 71, 41))
			self.secmotarr2.setGeometry(QtCore.QRect(529, 129, 51, 41))
			self.thirdmotarr2.setGeometry(QtCore.QRect(712, 290, 51, 41))
			self.fourthmotarr1.setGeometry(QtCore.QRect(528, 268, 71, 41))
			self.movingleft.setGeometry(QtCore.QRect(90, 400, 251, 171))
		elif msg.axes[0]<0:
			self.fmotarr2.setGeometry(QtCore.QRect(736, 127, 61, 51))
			self.secmotarr1.setGeometry(QtCore.QRect(550, 102, 61, 51))
			self.thirdmotarr1.setGeometry(QtCore.QRect(733, 263, 61, 51))
			self.fourthmotarr2.setGeometry(QtCore.QRect(553, 290, 61, 51))
			self.movingright.setGeometry(QtCore.QRect(90, 400, 251, 171))
		elif msg.axes[1]> 0:
			self.fmotarr1.setGeometry(QtCore.QRect(711, 107, 71, 41))
			self.secmotarr1.setGeometry(QtCore.QRect(550, 102, 61, 51))
			self.thirdmotarr1.setGeometry(QtCore.QRect(733, 263, 61, 51))
			self.fourthmotarr1.setGeometry(QtCore.QRect(528, 268, 71, 41))
			self.movingforward.setGeometry(90, 400, 251, 171)

		elif msg.axes[1]<0:
			self.fmotarr2.setGeometry(QtCore.QRect(736, 127, 61, 51))
			self.secmotarr2.setGeometry(QtCore.QRect(529, 129, 51, 41))
			self.thirdmotarr2.setGeometry(QtCore.QRect(712, 290, 51, 41))
			self.fourthmotarr2.setGeometry(QtCore.QRect(553, 290, 61, 51))
			self.movingback.setGeometry(90, 400, 251, 171)

		elif msg.axes[2] <0:
			self.fmotarr2.setGeometry(QtCore.QRect(736, 127, 61, 51))
			self.secmotarr1.setGeometry(QtCore.QRect(550, 102, 61, 51))
			self.thirdmotarr2.setGeometry(QtCore.QRect(712, 290, 51, 41))
			self.fourthmotarr1.setGeometry(QtCore.QRect(528, 268, 71, 41))
			self.rotatingright.setGeometry(95, 460, 241, 51)

		elif msg.axes[2]>0:
			self.fmotarr1.setGeometry(QtCore.QRect(711, 107, 71, 41))
			self.secmotarr2.setGeometry(QtCore.QRect(529, 129, 51, 41))
			self.thirdmotarr1.setGeometry(QtCore.QRect(733, 263, 61, 51))
			self.fourthmotarr2.setGeometry(QtCore.QRect(553, 290, 61, 51))
			self.rotatingleft.setGeometry(95, 460, 241, 51)

		elif msg.buttons[0]==1:
			self.gripperc.setGeometry(QtCore.QRect(77, -460, 251, 171))
			self.grippero.setGeometry(QtCore.QRect(77, 460, 251, 171))

		elif msg.axes[5]==1:
			self.camservo1.setGeometry(QtCore.QRect(250, 132, 46, 36))
			self.camservo2.setGeometry(QtCore.QRect(216, -132, 46, 36))
		elif msg.axes[5]==-1:
			self.camservo1.setGeometry(QtCore.QRect(250, -132, 46, 36))
			self.camservo2.setGeometry(QtCore.QRect(216, 132, 46, 36))


		else:
			
			if msg.axes[3] < 1 and msg.axes[3] > -1:
				if msg.axes[3] < self.oldvalue:
					self.movingdown.setGeometry(QtCore.QRect(90, 400, 251, 171))
					self.fifthmotarr2.setGeometry(1041, 210, 51, 51)
					self.sixthmotarr2.setGeometry(865, 211, 51, 51)
					self.oldvalue = msg.axes[3]
					QtTest.QTest.qWait(60)
					self.fifthmotarr2.setGeometry(1041, -210, 51, 51)
					self.sixthmotarr2.setGeometry(863, -211, 51, 51)
					self.movingdown.setGeometry(QtCore.QRect(90, -420, 251, 171))
				elif msg.axes[3] > self.oldvalue:
					self.movingup.setGeometry(QtCore.QRect(90, 400, 251, 171))
					self.fifthmotarr1.setGeometry(QtCore.QRect(1041, 169, 61, 61))
					self.sixthmotarr1.setGeometry(QtCore.QRect(864, 168, 61, 61))
					self.oldvalue = msg.axes[3]
					QtTest.QTest.qWait(60)
					self.fifthmotarr1.setGeometry(QtCore.QRect(1041, -169, 61, 61))
					self.sixthmotarr1.setGeometry(QtCore.QRect(863, -170, 61, 61))    
	    				self.movingup.setGeometry(QtCore.QRect(90, -420, 251, 171))
				
			self.rotatingright.setGeometry(98, -480, 241, 51)
			self.rotatingright.setGeometry(98, -480, 241, 51)
			self.movingforward.setGeometry(90, -420, 251, 171)
			self.rotatingleft.setGeometry(98, -480, 241, 51)
			self.movingback.setGeometry(90, -420, 251, 171)
			self.thirdmotarr2.setGeometry(QtCore.QRect(712, -290, 51, 41))
			self.fourthmotarr2.setGeometry(QtCore.QRect(553, -290, 61, 51))
			self.fmotarr1.setGeometry(QtCore.QRect(711, -107, 71, 41))
			self.secmotarr1.setGeometry(QtCore.QRect(550, -102, 61, 51))
			self.thirdmotarr1.setGeometry(QtCore.QRect(733, -263, 61, 51))
			self.fourthmotarr1.setGeometry(QtCore.QRect(528, -268, 71, 41))
			self.fmotarr2.setGeometry(QtCore.QRect(736, -127, 61, 51))
			self.secmotarr2.setGeometry(QtCore.QRect(529, -129, 51, 41))
			self.camservo1.setGeometry(QtCore.QRect(229, -266, 61, 31))
			self.camservo2.setGeometry(QtCore.QRect(229, -266, 61, 31))
			self.movingleft.setGeometry(QtCore.QRect(90, -420, 251, 171))
			self.movingright.setGeometry(QtCore.QRect(90, -420, 251, 171))
			self.grippero.setGeometry(QtCore.QRect(77, -460, 251, 171))
			self.gripperc.setGeometry(QtCore.QRect(77, 460, 251, 171))

	elif (self.micromode.isChecked()):


		if msg.buttons[2]==1:
        		self.dcmotorb.setGeometry(QtCore.QRect(217, -196, 51, 101))
        		self.dcmotorf.setGeometry(QtCore.QRect(239, 195, 51, 101))
		elif msg.buttons[3]==1:
        		self.dcmotorb.setGeometry(QtCore.QRect(217, 196, 51, 101))
        		self.dcmotorf.setGeometry(QtCore.QRect(239, -195, 51, 101))
		elif msg.axes[4]==-1:
			self.servo1.setGeometry(QtCore.QRect(250, 264, 46, 36))
			self.servo2.setGeometry(QtCore.QRect(216, -263, 46, 36))
		elif msg.axes[4]==1:
			self.servo1.setGeometry(QtCore.QRect(250, -264, 46, 36))
			self.servo2.setGeometry(QtCore.QRect(216, 263, 46, 36))
		elif msg.buttons[10] ==1:
			self.led.setGeometry(QtCore.QRect(229, 273, 51, 101))

		elif msg.buttons[11] ==1:
			self.led.setGeometry(QtCore.QRect(229, -273, 51, 101))
		else:
        		self.dcmotorb.setGeometry(QtCore.QRect(217, -196, 51, 101))
        		self.dcmotorf.setGeometry(QtCore.QRect(239, -195, 51, 101))
			self.servo1.setGeometry(QtCore.QRect(229, -227, 61, 31))
			self.servo2.setGeometry(QtCore.QRect(229, -227, 61, 31))
	elif (self.offmode.isChecked()):

		self.microrov.setGeometry(QtCore.QRect(228, -147, 51, 101))
		pass
	else:
		pass




import Backgroundandfixedstuff

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()

    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



