from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
import rospy
import time
from sensor_msgs.msg import Joy
from std_msgs.msg import Int32
import sys
import subprocess
import paramiko

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 570)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 981, 581))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 48, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 25, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 38, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(186, 189, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 48, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 25, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 38, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 48, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 25, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 38, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 38, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 165, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.MainGUI = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        self.MainGUI.setPalette(palette)
        self.MainGUI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MainGUI.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.MainGUI.setObjectName("MainGUI")
        self.mainGU_background = QLabel(self.MainGUI)
        self.mainGU_background.setGeometry(QtCore.QRect(0, 0, 981, 541))
        self.mainGU_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainGU_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainGU_background.setLineWidth(6)
        self.mainGU_background.setText("")
        self.mainGU_background.setPixmap(QtGui.QPixmap(":/newPrefix/Background+fixedstuff.png"))
        self.mainGU_background.setScaledContents(True)
        self.mainGU_background.setWordWrap(False)
        self.mainGU_background.setOpenExternalLinks(False)
        self.mainGU_background.setObjectName("mainGU_background")
        self.pushButton = QtWidgets.QPushButton(self.MainGUI)
        self.pushButton.setGeometry(QtCore.QRect(110, 124, 75, 20))
        self.pushButton.clicked.connect(self.raspberry_connect)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.joystick_button = QtWidgets.QPushButton(self.MainGUI)
        self.joystick_button.setGeometry(QtCore.QRect(178, 160, 14, 26))
        self.joystick_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joystick_button.setText("")
        self.joystick_button.setFlat(True)
        self.joystick_button.clicked.connect(self.joystick_command)
        self.joystick_button.setObjectName("joystick_button")
        self.lineEdit = QtWidgets.QLineEdit(self.MainGUI)
        self.lineEdit.setGeometry(QtCore.QRect(60, 95, 171, 25))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.rasp_ip = "192.168.0.101"
        self.lineEdit.setText(self.rasp_ip)
        self.normal_moce_button = QtWidgets.QRadioButton(self.MainGUI)
        self.normal_moce_button.setGeometry(QtCore.QRect(264, 153, 16, 23))
        self.normal_moce_button.setText("")
        self.normal_moce_button.setObjectName("normal_moce_button")
        self.auto_mode_button = QtWidgets.QRadioButton(self.MainGUI)
        self.auto_mode_button.setGeometry(QtCore.QRect(264, 196, 16, 23))
        self.auto_mode_button.setText("")
        self.auto_mode_button.setObjectName("auto_mode_button")
        self.off_mode_button = QtWidgets.QRadioButton(self.MainGUI)
        self.off_mode_button.setGeometry(QtCore.QRect(264, 238, 16, 23))
        self.off_mode_button.setText("")
        self.off_mode_button.setChecked(True)
        self.off_mode_button.setObjectName("off_mode_button")
        
        self.dcmotor_up = QLabel(self.MainGUI)
        self.dcmotor_up.setGeometry(QtCore.QRect(187, -186, 39, 36))
        self.dcmotor_up.setText("")
        self.dcmotor_up.setPixmap(QtGui.QPixmap("90.png"))
        self.dcmotor_up.setScaledContents(True)
        self.dcmotor_up.setObjectName("dcmotor_up")
        self.dcmotor_down = QLabel(self.MainGUI)
        self.dcmotor_down.setGeometry(QtCore.QRect(171, -187, 35, 35))
        self.dcmotor_down.setText("")
        self.dcmotor_down.setPixmap(QtGui.QPixmap("-90.png"))
        self.dcmotor_down.setScaledContents(True)
        self.dcmotor_down.setObjectName("dcmotor_down")
        self.gripperclosing_left = QLabel(self.MainGUI)
        self.gripperclosing_left.setGeometry(QtCore.QRect(169, -220, 27, 31))
        self.gripperclosing_left.setText("")
        self.gripperclosing_left.setPixmap(QtGui.QPixmap("gripperbarrowleft.png"))
        self.gripperclosing_left.setScaledContents(True)
        self.gripperclosing_left.setObjectName("gripperclosing_left")
        
        self.m1_up = QLabel(self.MainGUI)
        self.m1_up.setGeometry(QtCore.QRect(450, -90, 41, 41))
        self.m1_up.setText("")
        self.m1_up.setPixmap(QtGui.QPixmap("45.png"))
        self.m1_up.setScaledContents(True)
        self.m1_up.setObjectName("m1_up")
        self.m1_down = QLabel(self.MainGUI)
        self.m1_down.setGeometry(QtCore.QRect(432, -108, 41, 41))
        self.m1_down.setText("")
        self.m1_down.setPixmap(QtGui.QPixmap("-135.png"))
        self.m1_down.setScaledContents(True)
        self.m1_down.setObjectName("m1_down")
        
        
        
        self.m2_up = QLabel(self.MainGUI)
        self.m2_up.setGeometry(QtCore.QRect(580, -90, 41, 41))
        self.m2_up.setText("")
        self.m2_up.setPixmap(QtGui.QPixmap("135.png"))
        self.m2_up.setScaledContents(True)
        self.m2_up.setObjectName("m2_up")
        self.m2_down = QLabel(self.MainGUI)
        self.m2_down.setGeometry(QtCore.QRect(603, -112, 41, 41))
        self.m2_down.setText("")
        self.m2_down.setPixmap(QtGui.QPixmap("-45.png"))
        self.m2_down.setScaledContents(True)
        self.m2_down.setObjectName("m2_down")
        
        
        
        
        
        
        self.m3_up = QLabel(self.MainGUI)
        self.m3_up.setGeometry(QtCore.QRect(430, -214, 41, 41))
        self.m3_up.setText("")
        self.m3_up.setPixmap(QtGui.QPixmap("135.png"))
        self.m3_up.setScaledContents(True)
        self.m3_up.setObjectName("m3_up")
        self.m3_down = QLabel(self.MainGUI)
        self.m3_down.setGeometry(QtCore.QRect(452, -236, 41, 41))
        self.m3_down.setText("")
        self.m3_down.setPixmap(QtGui.QPixmap("-45.png"))
        self.m3_down.setScaledContents(True)
        self.m3_down.setObjectName("m3_down")
        
        
        self.m4_up = QLabel(self.MainGUI)
        self.m4_up.setGeometry(QtCore.QRect(598, -214, 41, 41))
        self.m4_up.setText("")
        self.m4_up.setPixmap(QtGui.QPixmap("45.png"))
        self.m4_up.setScaledContents(True)
        self.m4_up.setObjectName("m4_up")
        self.m4_down = QLabel(self.MainGUI)
        self.m4_down.setGeometry(QtCore.QRect(580, -232, 41, 41))
        self.m4_down.setText("")
        self.m4_down.setPixmap(QtGui.QPixmap("-135.png"))
        self.m4_down.setScaledContents(True)
        self.m4_down.setObjectName("m4_down")
        
        
        self.m5_up = QLabel(self.MainGUI)
        self.m5_up.setGeometry(QtCore.QRect(707, -143, 41, 41))
        self.m5_up.setText("")
        self.m5_up.setPixmap(QtGui.QPixmap("90.png"))
        self.m5_up.setScaledContents(True)
        self.m5_up.setObjectName("m5_up")
        self.m5_down = QLabel(self.MainGUI)
        self.m5_down.setGeometry(QtCore.QRect(708, -174, 41, 41))
        self.m5_down.setText("")
        self.m5_down.setPixmap(QtGui.QPixmap("-90.png"))
        self.m5_down.setScaledContents(True)
        self.m5_down.setObjectName("m5_down")
        
        
        self.m6_up = QLabel(self.MainGUI)
        self.m6_up.setGeometry(QtCore.QRect(850, -144, 41, 41))
        self.m6_up.setText("")
        self.m6_up.setPixmap(QtGui.QPixmap("90.png"))
        self.m6_up.setScaledContents(True)
        self.m6_up.setObjectName("m6_up")
        self.m6_down = QLabel(self.MainGUI)
        self.m6_down.setGeometry(QtCore.QRect(850, -174, 41, 41))
        self.m6_down.setText("")
        self.m6_down.setPixmap(QtGui.QPixmap("-90.png"))
        self.m6_down.setScaledContents(True)
        self.m6_down.setObjectName("m6_down")
        
        
        
        
        self.gripperclosing_right = QLabel(self.MainGUI)
        self.gripperclosing_right.setGeometry(QtCore.QRect(196, -220, 27, 31))
        self.gripperclosing_right.setText("")
        self.gripperclosing_right.setPixmap(QtGui.QPixmap("gripperbarrowright.png"))
        self.gripperclosing_right.setScaledContents(True)
        self.gripperclosing_right.setObjectName("gripperclosing_right")
        self.gripperopen_left = QLabel(self.MainGUI)
        self.gripperopen_left.setGeometry(QtCore.QRect(175, -227, 26, 31))
        self.gripperopen_left.setText("")
        self.gripperopen_left.setPixmap(QtGui.QPixmap("grippersarrowleft.png"))
        self.gripperopen_left.setScaledContents(True)
        self.gripperopen_left.setObjectName("gripperopen_left")
        self.gripperopen_right = QLabel(self.MainGUI)
        self.gripperopen_right.setGeometry(QtCore.QRect(190, -227, 26, 31))
        self.gripperopen_right.setText("")
        self.gripperopen_right.setPixmap(QtGui.QPixmap("grippersarrowright.png"))
        self.gripperopen_right.setScaledContents(True)
        self.gripperopen_right.setObjectName("gripperopen_right")
        self.raspberry_state = QLabel(self.MainGUI)
        self.raspberry_state.setGeometry(QtCore.QRect(192, -64, 41, 41))
        self.raspberry_state.setText("")
        self.raspberry_state.setPixmap(QtGui.QPixmap("Yello Dot.png"))
        self.raspberry_state.setScaledContents(True)
        self.raspberry_state.setObjectName("raspberry_state")
        self.jostick_state = QLabel(self.MainGUI)
        self.jostick_state.setGeometry(QtCore.QRect(188, -153, 41, 41))
        self.jostick_state.setText("")
        self.jostick_state.setPixmap(QtGui.QPixmap("Yello Dot.png"))
        self.jostick_state.setScaledContents(True)
        self.jostick_state.setObjectName("jostick_state")
        self.vertical_gripper_state = QLabel(self.MainGUI)
        self.vertical_gripper_state.setGeometry(QtCore.QRect(161, -252, 31, 31))
        self.vertical_gripper_state.setText("")
        self.vertical_gripper_state.setPixmap(QtGui.QPixmap("Yello Dot.png"))
        self.vertical_gripper_state.setScaledContents(True)
        self.vertical_gripper_state.setObjectName("vertical_gripper_state")
        self.horizontal_gripper_state = QLabel(self.MainGUI)
        self.horizontal_gripper_state.setGeometry(QtCore.QRect(112, -252, 31, 31))
        self.horizontal_gripper_state.setText("")
        self.horizontal_gripper_state.setPixmap(QtGui.QPixmap("Yello Dot.png"))
        self.horizontal_gripper_state.setScaledContents(True)
        self.horizontal_gripper_state.setObjectName("horizontal_gripper_state")
        self.tabWidget.addTab(self.MainGUI, "")
        self.subGUI = QtWidgets.QWidget()
        self.subGUI.setObjectName("subGUI")
        self.subGUI_background = QLabel(self.subGUI)
        self.subGUI_background.setGeometry(QtCore.QRect(0, 0, -981, 541))
        self.subGUI_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subGUI_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subGUI_background.setLineWidth(6)
        self.subGUI_background.setText("")
        self.subGUI_background.setPixmap(QtGui.QPixmap(":/vision_tab/vision_tab.png"))
        self.subGUI_background.setScaledContents(True)
        self.subGUI_background.setWordWrap(False)
        self.subGUI_background.setOpenExternalLinks(False)
        self.subGUI_background.setObjectName("subGUI_background")
        self.camera_1_button = QtWidgets.QPushButton(self.subGUI)
        self.camera_1_button.setGeometry(QtCore.QRect(168, -99, 151, 31))
        self.camera_1_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_1_button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.camera_1_button.setText("")
        self.camera_1_button.setFlat(True)
        self.camera_1_button.setObjectName("camera_1_button")
        self.camera_2_button = QtWidgets.QPushButton(self.subGUI)
        self.camera_2_button.setGeometry(QtCore.QRect(412, -98, 151, 31))
        self.camera_2_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_2_button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.camera_2_button.setText("")
        self.camera_2_button.setFlat(True)
        self.camera_2_button.setObjectName("camera_2_button")
        self.camera_3_button = QtWidgets.QPushButton(self.subGUI)
        self.camera_3_button.setGeometry(QtCore.QRect(666, -98, 151, 31))
        self.camera_3_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.camera_3_button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.camera_3_button.setText("")
        self.camera_3_button.setFlat(True)
        self.camera_3_button.setObjectName("camera_3_button")
        self.tabWidget.addTab(self.subGUI, "")
        
        
        self.movingback = QLabel(self.centralwidget)
        self.movingback.setGeometry(67, -365, 220, 140)
        self.movingback.setText((""))
        self.movingback.setPixmap(QtGui.QPixmap(("Moving Backward.png")))
        self.movingback.setScaledContents(True)
        self.movingback.setObjectName(("movingback"))
        self.movingdown = QLabel(self.centralwidget)
        self.movingdown.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingdown.setText((""))
        self.movingdown.setPixmap(QtGui.QPixmap(("Moving Downward.png")))
        self.movingdown.setScaledContents(True)
        self.movingdown.setObjectName(("movingdown"))
        self.movingforward = QLabel(self.centralwidget)
        self.movingforward.setGeometry(67, -365, 220, 140)
        self.movingforward.setText((""))
        self.movingforward.setPixmap(QtGui.QPixmap(("Moving Forward.png")))
        self.movingforward.setScaledContents(True)
        self.movingforward.setObjectName(("movingforward"))
        self.movingleft = QLabel(self.centralwidget)
        self.movingleft.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingleft.setText((""))
        self.movingleft.setPixmap(QtGui.QPixmap(("Moving Left.png")))
        self.movingleft.setScaledContents(True)
        self.movingleft.setObjectName(("movingleft"))
        self.movingright = QLabel(self.centralwidget)
        self.movingright.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingright.setText((""))
        self.movingright.setPixmap(QtGui.QPixmap(("Moving Right.png")))
        self.movingright.setScaledContents(True)
        self.movingright.setObjectName(("movingright"))
        self.movingup = QLabel(self.centralwidget)
        self.movingup.setGeometry(QtCore.QRect(90, -420, 251, 171))
        self.movingup.setText((""))
        self.movingup.setPixmap(QtGui.QPixmap(("Moving Upward.png")))
        self.movingup.setScaledContents(True)
        self.movingup.setObjectName(("movingup"))
        self.rotatingleft = QLabel(self.centralwidget)
        self.rotatingleft.setGeometry(98, -480, 241, 51)
        self.rotatingleft.setText((""))
        self.rotatingleft.setPixmap(QtGui.QPixmap(("RotatingLeft.png")))
        self.rotatingleft.setScaledContents(True)
        self.rotatingleft.setObjectName(("rotatingleft"))
        self.rotatingright = QLabel(self.centralwidget)
        self.rotatingright.setGeometry(98, -480, 241, 51)
        self.rotatingright.setText((""))
        self.rotatingright.setPixmap(QtGui.QPixmap(("RotatingRight.png")))
        self.rotatingright.setScaledContents(True)
        self.rotatingright.setObjectName(("rotatingright"))
        self.grippero = QLabel(self.centralwidget)
        self.grippero.setGeometry(QtCore.QRect(90, -460, 251, 171))
        self.grippero.setText((""))
        self.grippero.setPixmap(QtGui.QPixmap(("Gripperopen.png")))
        self.grippero.setObjectName(("gripperopen"))
        self.gripperc = QLabel(self.centralwidget)
        self.gripperc.setGeometry(QtCore.QRect(77, -460, 251, 171))
        self.gripperc.setText((""))
        self.gripperc.setPixmap(QtGui.QPixmap(("Gripperclosed.png")))
        self.gripperc.setObjectName(("gripperclosed"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainGUI), _translate("MainWindow", "Main GUI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.subGUI), _translate("MainWindow", "Sub GUI"))
        self.roscore_command()
        self.listener() 
        
    def roscore_command(self):
        self.command = subprocess.Popen(['roscore'])
    def joystick_command(self):
        self.command = subprocess.Popen(['rosrun', 'joy', 'joy_node'])
        self.jostick_state.setGeometry(QtCore.QRect(188, 153, 41, 41))
    def raspberry_connect(self):
        self.raspberry_state.setGeometry(QtCore.QRect(192, 64, 41, 41))
        self.command = subprocess.Popen([f"ssh -t pi@{self.rasp_ip} 'source ros_catkin_ws/devel/setup.bash && export ROS_MASTER_URI=http://192.168.0.100:11311 && cd && python3 Desktop/listenerfinal.py' "], shell = True)
       
    def listener (self):
        rospy.init_node('joysub', anonymous=True)
        rospy.Subscriber("joy", Joy, self.callback)
    def callback(self,msg):
        if (self.normal_moce_button.isChecked()):
            #LEFT - RIGHT
            if msg.axes[0]>0:    #LEFT
                self.m1_down.setGeometry(QtCore.QRect(432, 108, 41, 41))
                self.m2_up.setGeometry(QtCore.QRect(580, 90, 41, 41))
                self.m3_up.setGeometry(QtCore.QRect(430, 214, 41, 41))           
                self.m4_down.setGeometry(QtCore.QRect(580, 232, 41, 41))

                self.movingleft.setGeometry(QtCore.QRect(54, 350, 251, 171))
            elif (msg.axes[0]<0):    #RIGHT
                self.m1_up.setGeometry(QtCore.QRect(450, 90, 41, 41))
                self.m2_down.setGeometry(QtCore.QRect(603, 112, 41, 41))
                self.m4_up.setGeometry(QtCore.QRect(598, 214, 41, 41))
                self.m3_down.setGeometry(QtCore.QRect(452, 236, 41, 41))
                self.movingright.setGeometry(QtCore.QRect(54, 350, 251, 171))  
            #FORWARD-BACKWARD
            elif msg.axes[1]>0:    #FORWARD
                self.m2_up.setGeometry(QtCore.QRect(580, 90, 41, 41))
                self.m4_up.setGeometry(QtCore.QRect(598, 214, 41, 41))
                self.m1_up.setGeometry(QtCore.QRect(450, 90, 41, 41))
                self.m3_up.setGeometry(QtCore.QRect(430, 214, 41, 41)) 
                self.movingforward.setGeometry(67, 365, 220, 140)
            elif msg.axes[1]<0:    #BACKWARD
                self.m1_down.setGeometry(QtCore.QRect(432, 108, 41, 41))
                self.m3_down.setGeometry(QtCore.QRect(452, 236, 41, 41))
                self.m2_down.setGeometry(QtCore.QRect(603, 112, 41, 41))
                self.m4_down.setGeometry(QtCore.QRect(580, 232, 41, 41))
                self.movingback.setGeometry(67, 365, 220, 140)
            #ROTATE RIGHT - ROTATE LEFT
            elif msg.axes[2]<0:    #ROTATE RIGHT
                self.m4_down.setGeometry(QtCore.QRect(580, 232, 41, 41))
                self.m3_up.setGeometry(QtCore.QRect(430, 214, 41, 41)) 
                self.m1_up.setGeometry(QtCore.QRect(450, 90, 41, 41))
                self.m2_down.setGeometry(QtCore.QRect(603, 112, 41, 41))
                self.rotatingright.setGeometry(63, 410, 230, 48)
            elif msg.axes[2]>0:    #ROTATE LEFT
                self.m1_down.setGeometry(QtCore.QRect(432, 108, 41, 41))
                self.m4_up.setGeometry(QtCore.QRect(598, 214, 41, 41))
                self.m3_down.setGeometry(QtCore.QRect(452, 236, 41, 41))
                self.m2_up.setGeometry(QtCore.QRect(580, 90, 41, 41))
                self.rotatingleft.setGeometry(63, 410, 230, 48)
            #UP - DOWN
            elif msg.axes[3]>0:    #UP
                self.m5_up.setGeometry(QtCore.QRect(707, 143, 41, 41))
                self.m6_up.setGeometry(QtCore.QRect(850, 144, 41, 41))
                self.movingup.setGeometry(QtCore.QRect(63, 390, 230, 95))
            elif msg.axes[3]<0:    #DOWN
                self.m5_down.setGeometry(QtCore.QRect(708, 174, 41, 41))
                self.m6_down.setGeometry(QtCore.QRect(850, 174, 41, 41))
                self.movingdown.setGeometry(QtCore.QRect(63, 390, 230, 95))
            
            else:
                self.m1_up.setGeometry(QtCore.QRect(450, -90, 41, 41))
                self.m1_down.setGeometry(QtCore.QRect(432, -108, 41, 41))
                self.m2_up.setGeometry(QtCore.QRect(580, -90, 41, 41))
                self.m2_down.setGeometry(QtCore.QRect(603, -112, 41, 41))
                self.m3_up.setGeometry(QtCore.QRect(430, -214, 41, 41))     
                self.m3_down.setGeometry(QtCore.QRect(452, -236, 41, 41))
                self.m4_up.setGeometry(QtCore.QRect(598, -214, 41, 41))  
                self.m4_down.setGeometry(QtCore.QRect(580, -232, 41, 41))
                self.m5_up.setGeometry(QtCore.QRect(707, -143, 41, 41))
                self.m5_down.setGeometry(QtCore.QRect(708, -174, 41, 41))
                self.m6_up.setGeometry(QtCore.QRect(850, -144, 41, 41))
                self.m6_down.setGeometry(QtCore.QRect(850, -174, 41, 41))
                self.movingright.setGeometry(QtCore.QRect(54, -350, 251, 171))
                self.movingleft.setGeometry(QtCore.QRect(54, -350, 251, 171))
                self.movingback.setGeometry(67, -365, 220, 140)
                self.movingforward.setGeometry(67, -365, 220, 140)
                self.rotatingleft.setGeometry(54, -350, 251, 171)
                self.rotatingright.setGeometry(54, -350, 251, 171)       
                self.movingup.setGeometry(QtCore.QRect(90, -420, 251, 171))
                self.movingdown.setGeometry(QtCore.QRect(90, -420, 251, 171))


          
import Backgroundadfixedstuff_rc
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_MainWindow()
    w = QtWidgets.QMainWindow()
    ex.setupUi(w)
    w.show()
    sys.exit(app.exec_())
    exit_command = subprocess.Popen(['killall', '-9', 'rosmaster'])
    
